name: java with Gradle

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Source Checkout
        uses: actions/checkout@v2

      - name: Setup JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      # jar file build and permission
      - name: Grant Jar
        run: chmod +x gradlew

      - name: Build Jar
        run: ./gradlew build bootJar

      # Setup Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Additional steps for docker image build can be added here
      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # build 
      - name: Push Image
        uses: docker/build-push-action@v2
        with:
          context: ./
          # Dockerfile이 있는 위치입니다.
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/gitaction_back:${{github.sha}}
